server:
  port: 9523
spring:
  application:
    name: training
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://:3306/training?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: 
    password: 
  redis:
    host: 
    port: 6379
    username: 
    password: 
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml


